test_site/main/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'main'

urlpatterns = [
    # EN

    path('en/cybersport', views.index, name='cybersport'),
    path('en/it', views.it, name='it'),
    path('en/cryptocurrency', views.crypto, name='cryptocurrency'),

    path('en/cryptocurrency/' + '<int:article_id>', views.detail, name='detailCrypto'),

    path('en/cryptocurrency/graph/' + '<str:cryptocurrency_name>', views.cryptograph, name='cryptoGraph'),

    path('en/it/' + '<int:article_id>', views.detail, name='detailIT'),

    path('en/cybersport/' + '<int:article_id>', views.detail, name='detailCybersport'),

    path('en/coding', views.compile, name='compile'),

    path('en/profile', views.profile, name='profile'),

    path('en/login', views.user_login, name='login'),

    path('en/register', views.register, name='register'),
    # RU

    path('ru/cybersport', views.indexru, name='cybersportRu'),
    path('ru/it', views.itru, name='itRu'),
    path('ru/cryptocurrency', views.cryptoru, name='cryptocurrencyRu'),

    path('ru/cryptocurrency/' + '<int:article_id>', views.detailru, name='detailCryptoRu'),

    path('ru/cryptocurrency/graph/' + '<str:cryptocurrency_name>', views.cryptographru, name='cryptoGraphRu'),

    path('ru/it/' + '<int:article_id>', views.detailru, name='detailITRu'),

    path('ru/cybersport/' + '<int:article_id>', views.detailru, name='detailCybersportRu'),

    path('ru/coding', views.compileru, name='compileRu'),

    path('ru/profile', views.profileru, name='profileRu'),

    path('ru/login', views.user_loginru, name='loginRu'),

    path('ru/register', views.registerru, name='registerRu'),

]

urlpatterns += staticfiles_urlpatterns()

test_site/test_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls')),
                  path('api/', include('project_api.urls')),
                  path("accounts/", include("django.contrib.auth.urls")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

test_site/main/models.py
from django.db import models


class Article(models.Model):
    article_type = models.CharField('article type', max_length=50)
    article_title = models.CharField('article name', max_length=200)
    article_text = models.TextField('article text')
    publishing_date = models.DateTimeField('publishing date')


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment_author = models.CharField('comment author', max_length=100)
    comment_text = models.TextField('comment text')


class Code(models.Model):
    code = models.TextField('code')
    publishing_date = models.DateTimeField('publishing date')

test_site/main/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class RegisterUser(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

test_site/main/views.py
import json
import datetime
import requests
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from .forms import RegisterUser, LoginForm
from .models import Article, Code
from django.contrib.auth import authenticate, login


def index(request):
    latest_articles = Article.objects.filter(article_type="Cybersport").order_by('-publishing_date')[:10]
    return render(request, 'main/index.html', {'latest_articles': latest_articles})


def it(request):
    latest_articles = Article.objects.filter(article_type="IT").order_by('-publishing_date')[:10]
    return render(request, 'main/it.html', {'latest_articles': latest_articles})


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("No Page was found!")
    return render(request, "main/detail.html", {'article': a})


def crypto(request):
    header = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36'}
    url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false'
    api_data = requests.get(url=url, headers=header).json()
    latest_articles = Article.objects.filter(article_type="Cryptocurrency").order_by('-publishing_date')[:10]
    return render(request, 'main/crypto.html', {'latest_articles': latest_articles, 'api_data': api_data})


def compile(request):
    latest_codes = Code.objects.order_by('-publishing_date')[:10]
    if request.method == "POST":
        shared_code = request.POST.get('share_code', False)
        code = request.POST.get('code', False)
        submit = request.POST.get('submit_code', False)
        language = request.POST.get('language_select', False)
        if submit and code:
            path = "https://api.jdoodle.com/v1/execute"
            params = {
                "script": code,
                "stdin": "",
                "language": language,
                "versionIndex": "0",
                "clientId": "eea45300d8deecc52a25aa145b624cdc",
                "clientSecret": "8a188eb5edb8802a1b740a4dc0aceb2dc29439a1d0f3034c9be6ee404cddb6a7"
            }
            response = requests.post(path, headers={"Content-Type": "application/json"}, data=json.dumps(params))
            return render(request, 'main/compile.html',
                          {'output': response.json(), 'user_code': code, 'latest_codes': latest_codes})
        if shared_code and code:
            new_code = Code(code=code, publishing_date=datetime.datetime.now())
            new_code.save()
            code = False
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return render(request, 'main/compile.html', {'latest_codes': latest_codes})


def profile(request):
    if request.user.is_authenticated:
        return render(request, 'main/profile.html')
    else:
        form = RegisterUser()
        return render(request, 'main/register.html', {'form': form})


def register(request):
    form = RegisterUser()
    if request.method == 'POST':
        form = RegisterUser(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return render(request, 'main/profile.html')
    return render(request, 'main/register.html', {'form': form})


def user_login(request):
    message = ""
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, 'main/profile.html')
                else:
                    message = "Disabled account"
            else:
                message = "Invalid login/password"
    else:
        form = LoginForm()
    return render(request, 'main/login.html', {'form': form, 'message': message})


def cryptograph(request, cryptocurrency_name):
    api_data = []
    for i in range(7):
        now = datetime.datetime.now() - datetime.timedelta(days=i)
        date = f"{now.day}-{now.month}-{now.year}"
        url = f'https://api.coingecko.com/api/v3/coins/{cryptocurrency_name}/history?date={date}&localization=en'
        api_data.append(requests.get(url=url).json())
    return render(request, 'main/cryptograph.html', {'data': api_data})


# RU

def indexru(request):
    if request.method == 'POST':
        is_register = request.POST.get('register', False)
        if is_register:
            form = RegisterUser(request.POST)
            if form.is_valid():
                form.save(commit=True)
    latest_articles = Article.objects.order_by('-publishing_date')[:10]
    return render(request, 'main/ru/indexru.html', {'latest_articles': latest_articles})


def itru(request):
    latest_articles = Article.objects.order_by('-publishing_date')[:10]
    return render(request, 'main/ru/itru.html', {'latest_articles': latest_articles})


def detailru(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Страница не была найдена!")
    return render(request, "main/ru/detailru.html", {'article': a})


def cryptoru(request):
    header = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36'}
    url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false'
    api_data = requests.get(url=url, headers=header).json()
    latest_articles = Article.objects.filter(article_type="Cryptocurrency").order_by('-publishing_date')[:10]
    return render(request, 'main/ru/cryptoru.html', {'latest_articles': latest_articles, 'api_data': api_data})


def compileru(request):
    latest_codes = Code.objects.order_by('-publishing_date')[:10]
    if request.method == "POST":
        shared_code = request.POST.get('share_code', False)
        code = request.POST.get('code', False)
        submit = request.POST.get('submit_code', False)
        language = request.POST.get('language_select', False)
        if submit and code:
            path = "https://api.jdoodle.com/v1/execute"
            params = {
                "script": code,
                "stdin": "",
                "language": language,
                "versionIndex": "0",
                "clientId": "eea45300d8deecc52a25aa145b624cdc",
                "clientSecret": "8a188eb5edb8802a1b740a4dc0aceb2dc29439a1d0f3034c9be6ee404cddb6a7"
            }
            response = requests.post(path, headers={"Content-Type": "application/json"}, data=json.dumps(params))
            return render(request, 'main/ru/compileru.html',
                          {'output': response.json(), 'user_code': code, 'latest_codes': latest_codes})
        if shared_code and code:
            new_code = Code(code=code, publishing_date=datetime.date.today())
            new_code.save()
            code = False
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return render(request, 'main/ru/compileru.html', {'latest_codes': latest_codes})


def profileru(request):
    if request.user.is_authenticated:
        return render(request, 'main/ru/profileru.html')
    else:
        form = RegisterUser()
        return render(request, 'main/ru/registerru.html', {'form': form})


def registerru(request):
    form = RegisterUser()
    if request.method == 'POST':
        form = RegisterUser(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return render(request, 'main/ru/profileru.html')
    return render(request, 'main/ru/registerru.html', {'form': form})


def user_loginru(request):
    message = ""
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, 'main/ru/profileru.html')
                else:
                    message = "Отключенный Аккаунт"
            else:
                message = "Неправильный логин/пароль"
    else:
        form = LoginForm()
    return render(request, 'main/ru/loginru.html', {'form': form, 'message': message})


def cryptographru(request, cryptocurrency_name):
    api_data = []
    for i in range(7):
        now = datetime.datetime.now() - datetime.timedelta(days=i)
        date = f"{now.day}-{now.month}-{now.year}"
        url = f'https://api.coingecko.com/api/v3/coins/{cryptocurrency_name}/history?date={date}&localization=en'
        api_data.append(requests.get(url=url).json())
    return render(request, 'main/ru/cryptographru.html', {'data': api_data})

test_site/main/templates/main/ru/baseru.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <script src="https://kit.fontawesome.com/e79a3aab28.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="apple-touch-icon" sizes="180x180" href="../images/apple-touch-icon.png">
    <link rel="icon" type="/image/png" sizes="32x32" href="../images/favicon-32x32.png">
    <link rel="icon" type="/image/png" sizes="16x16" href="../images/favicon-16x16.png">
    <link rel="manifest" href="/images/site.webmanifest">
    <link rel="mask-icon" href="../images/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ITQN</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    <link rel="shortcut icon" href="{%  static 'main/images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'main/css/profile.css' %}">
    </head>

<body class="bg">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid justify-content-center">
      <a class="navbar-brand" href="">IT Qazaqstan news<img src="{% static "main/images/favicon-32x32-r.png" %}" alt="home" /></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:itRu' %}">IT</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:cybersportRu' %}">КИБЕРСПОРТ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:cryptocurrencyRu' %}">КРИПТОВАЛЮТЫ</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'main:compileRu' %}">КОДИНГ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#footer">О НАС</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:profile' %}">ПРОФИЛЬ</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
        {% block content %}

        {% endblock %}


<!--  <div class="blur">-->
<!--      <div class="form-box">-->
<!--          <div class="form-buttons">-->
<!--              <button class="btn form-btn l" type="button" onclick="logining()">-->
<!--                  Вход-->
<!--              </button>-->
<!--              <button class="btn form-btn r" type="button" onclick="registering()">-->
<!--                  Регистрация-->
<!--              </button>-->
<!--          </div>-->
<!--          <div class="toggle">-->

<!--              <form method="POST" name="login">-->
<!--                  {% csrf_token %}-->

<!--                  <div class="login">-->
<!--                      <p>Имя Пользователя</p>-->
<!--                      {{form.username}}-->
<!--                      <p>Пароль:</p>-->
<!--                      {{form.password1}}-->
<!--                      <div>-->
<!--                          <input type="checkbox" id="stay" name="stay">-->
<!--                          <label for="stay">Остаться в системе</label>-->
<!--                      </div>-->
<!--                      <button class="btn" type="submit">Вход</button>-->
<!--                  </div>-->

<!--              </form>-->
<!--              <form method="POST" name="register">-->
<!--                  {% csrf_token %}-->
<!--                  <div class="register">-->
<!--                      <p>Имя Пользователя:</p>-->
<!--                      <input type="text" name="username">-->
<!--&lt;!&ndash;                      {{form.username}}&ndash;&gt;-->
<!--                      <p>Пароль:</p>-->
<!--                      <input type="password" name="password1">-->
<!--&lt;!&ndash;                      {{form.password1}}&ndash;&gt;-->
<!--                      <p>Подтвердите пароль:</p>-->
<!--                      <input type="password" name="password2">-->
<!--&lt;!&ndash;                      {{form.password2}}&ndash;&gt;-->
<!--&lt;!&ndash;                      <p>{{form.errors}}</p>&ndash;&gt;-->
<!--                      <button class="btn" type="submit" name="register">Sign up</button>-->
<!--                  </div>-->

<!--              </form>-->
<!--          </div>-->




    </div>
  </div>




    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script rel="javascript" src="{% static 'main/js/base.js' %}"></script>
    <script src="{% static 'main/js/profile.js' %}"></script>
    <script src = "https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script>
    {% block script %}

    {% endblock %}






</body>

</html>

test_site/main/templates/main/ru/compileru.html
{% extends 'main/ru/baseru.html' %}

{% block content %}

        <form action = "{% url 'main:compileRu' %}" method="POST">

<div class="compiler">
    <div class="language">
        {% csrf_token %}
        <p>Язык:</p>
        <select class="form-select" name="language_select" id="languages">
            <option value= "nodejs">NodeJS</option>
            <option value= "python3">python</option>
            <option value="java">java</option>
        </select>

</div>

<div class="coding">

    {% csrf_token %}
    <div class="input" ><h4>Ввод</h4><textarea class="form-control" name="code" cols = 80 rows = 20 >{{user_code}}</textarea>
        <div class="buttons">
            <button class="btn" type="submit" name="submit_code" value="submit_code">отправить код</button>
            <button class="btn" type="submit" name="share_code" value="share_code">поделиться кодом</button>

        </div>
    </div>


<div class="output"><h4>Output</h4><textarea class="form-control" cols = 80 rows = 20>{{output.output}}</textarea>

    <p>Код Статуса: {{output.statusCode}}</p>
    <p>Время ЦПУ: {{output.cpuTime}}</p>
    <p>{{output.error}}</p>

</div>
</div>
</div>
            </form>

<div class="container ">
    <h2>поделенные коды</h2>
    {% if latest_codes %}
    {% for code in latest_codes %}
    <div class="share">
            <h4>Автор:</h4>
            <textarea class="form-control" type="text" cols = 80 rows = 20 >{{code.code}}
                </textarea>
                <button class="btn" type="submit"></button></div>
    {% endfor %}
    {% endif %}
    </div>

</div>

{% endblock %}

test_site/main/templates/main/ru/cryptographru.html
{% extends 'main/ru/baseru.html' %}

{% block script %}

<script>
    var data = [];
    var labels = [];
    for (let i=0;i<7;i++){
        var day = document.getElementsByClassName("day")[i].innerHTML
        data.push(day)
    }
    console.log(data.type)

    const ctx = document.getElementById('myChart');
    const myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: ["1","2","3","4","5","6","7"],
            datasets: [{
                label: 'История изменения цен',
                data: data,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(153, 102, 255, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                    "rgba(54, 162, 235, 1)"
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
    </script>

{% endblock %}

{% block content %}
<canvas id="myChart" width="40" height="80"></canvas>

{% for api in data %}
<p class="day" style="display:none"> {{api.market_data.current_price.usd}} </p>
{% endfor %}

{% endblock %}

test_site/main/templates/main/ru/cryptoru.html
{% extends 'main/ru/baseru.html' %}

{% block content %}




{% if latest_articles %}


<div class ="container news">
    <h2>Новости Крипотовалют</h2>
    {% for article in latest_articles %}
    <div class="pin container-fluid">
        <div>
        <img src="https://upload.wikimedia.org/wikipedia/commons/a/a1/Mallard2.jpg" class="">
        <h4 class=""><a class="nav-link" href="{% url 'main:detailCrypto' article.id %}">{{article.article_title}}</a></h4>

    </div>

    <p>{{article.article_text}}</p>

    </div>
    {% endfor %}
</div>




    {% else %}
        Статьи не были найдены! :c
    {% endif %}

    <div class ="container">
        <h2>Курс Криптовалют</h2>
    <div class="crcarr">
    {% for crypto in api_data %}
    <div class = "crc">
    <a class="" href="{% url 'main:cryptoGraphRu' crypto.id %}">{{crypto.name}} <img src="{{crypto.image}}" class=""></a>
    <p>цена:{{crypto.current_price}}</p>
    <p>Рыночная капитализация:{{crypto.market_cap}}</p>
    </div>
    {% endfor %}
    </div>
</div>

    {% endblock %}

test_site/main/templates/main/ru/detailru.html
{% extends 'main/ru/baseru.html' %}

{% block content %}

    <h2> {{article.article_title}}</h2>
    <p>{{article.article_text}}</p>

{% endblock %}

test_site/main/templates/main/ru/indexru.html
{% extends 'main/ru/baseru.html' %}

{% block content %}

    {% if latest_articles %}

    <div class ="container news">
        <h2>Новости Киберспорта</h2>
        {% for article in latest_articles %}
        <div class="pin container-fluid">
            <div>
            <img src="https://upload.wikimedia.org/wikipedia/commons/a/a1/Mallard2.jpg" class="">
            <h4 class=""><a class="nav-link" href="{% url 'main:detailCybersport' article.id %}">{{article.article_title}}</a></h4>

        </div>

        <p>{{article.article_text}}</p>

        </div>
        {% endfor %}
    </div>

    {% else %}
        Статьи не были найдены! :c
    {% endif %}
{% endblock %}

test_site/main/templates/main/ru/itru.html
{% extends 'main/ru/baseru.html' %}

{% block content %}
{% if latest_articles %}

<div class ="container news">
    <h2>Новости IT</h2>
    {% for article in latest_articles %}
    <div class="pin container-fluid">
        <div>
        <img src="https://upload.wikimedia.org/wikipedia/commons/a/a1/Mallard2.jpg" class="">
        <h4 class=""><a class="nav-link" href="{% url 'main:detailIT' article.id %}">{{article.article_title}}</a></h4>

    </div>

    <p>{{article.article_text}}</p>

    </div>
    {% endfor %}
</div>

    {% else %}
        Статьи не были найдены! :c
    {% endif %}
{% endblock %}

test_site/main/templates/main/ru/loginru.html
{% extends 'main/ru/baseru.html' %}


{% load static %}

  {% block content %}

    <form method="POST" action = "{% url 'main:login' %}">
      {% csrf_token %}
      <div class="login">
          {{ form.as_p }}
        <p>{{message}}</p>
          <button class="btn" type="submit">Войти</button>
      </div>

  </form>

<link rel="stylesheet" href="{% static 'main/css/profile.css' %}">
{% endblock %}

test_site/main/templates/main/ru/profileru.html
{% extends 'main/ru/baseru.html' %}

{% load static %}
{% block content %}
<div class="profile">
{% if request.user.is_authenticated %}
  <p>{{request.user.username}}</p>
{% else %}
  <p>не авторизованный пользователь</p>
{% endif %}
<p><a href="{% url 'logout' %}">Выйти</a></p>
  </div>
{% endblock %}

test_site/main/templates/main/ru/registerru.html
{% extends 'main/ru/baseru.html' %}

{% load static %}

  {% block content %}

    <form method="POST" action="{% url 'main:registerRu' %}">
      {% csrf_token %}
      <div class="register">
          <p>Имя:</p>
                      {{form.username}}
          <p>Пароль:</p>
                      {{form.password1}}
          <p>Подтвердите пароль:</p>
                      {{form.password2}}
                      <p>{{form.errors}}</p>
          <button class="btn" type="submit" name="register">Зарегистрироваться</button>

      </div>

  </form>


<link rel="stylesheet" href="{% static 'main/css/profile.css' %}">
{% endblock %}